### ISSUE TITLE
Why are you including Vuex?

### ISSUE THREAD

**Issue by petervmeijgaard** [Daivasmara/To-Do-List#1]
Hi @Daivasmara!

I stumbled upon your todo application and saw that you are including Vuex in your project, but you're only initializing an empty store. It also seems that you don't use it in your main Vue file.

Is there a reason why you're including Vuex in this project? Do you intend to use it in the future?

**Comment by Daivasmara** [comment]
Hi @petervmeijgaard !
Ah yeah sorry, i was using state before, but then i decided to store the todos in localStorage instead. I'll remove those, thanks for noticing!

**Comment by petervmeijgaard** [comment]
Thanks for the quick response and clarification!
Keep up the good work 👍
