### ISSUE TITLE
Checkboxes don't do anything?

### ISSUE THREAD

**Issue by benmcm1994** [Daivasmara/To-Do-List#2]
Hi Daivasmara,

Are you aware that by checking the boxes and pressing delete results in only deleting the item you pressed delete on? It currently doesnt delete the checked items. Just a heads up, no idea if you intended to put in the multi-delete functionality, but the checkboxes would lead me to think you did :)

**Comment by Daivasmara** [comment]
Hi @benmcm1994 ,
The checkboxes are used as done mark. It's a to-do list, so unchecked means not done, and checked means done. Sorry if it purpose isnt clear enough and for the late replies. Thanks for the question!
